<a href="https://colab.research.google.com/github/yukinaga/image_classification/blob/main/section_1/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor
TensorはPyTorchにおいて最も基本となるデータ構造です。  
Tensorを操作するための様々なコードを、Google Colacoratoryで練習しましょう。

## PyTorchの確認
環境にインストール済みのパッケージを全て表示し、「torch」という名前でPyTorchがインストールされていることを確認します。

In [1]:
!pip list

Package                  Version
------------------------ ------------
anyio                    3.7.0
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    23.1.0
backcall                 0.2.0
beautifulsoup4           4.12.2
bleach                   6.0.0
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       2.1.1
colorama                 0.4.6
comm                     0.1.3
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
executing                1.2.0
fastjsonschema           2.17.1
filelock                 3.9.0
fqdn                     1.5.1
idna                     3.4
ipykernel                6.23.3
ipython                  8.14.0
ipython-genutils         0.2.0
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jsonpointer              2.4
jsonschema         

## Tensorを生成する
以下のコードは、torchの`tensor()`関数により、PythonのリストからTensorを生成します。    
type()により型の確認も行います。  

In [2]:
import torch

a = torch.tensor([12,13,14])
print(a, type(a))

tensor([12, 13, 14]) <class 'torch.Tensor'>


以下は、他の生成方法です。

In [3]:
print("--- 2次元のリストから生成 ---")
b = torch.tensor([[11, 12],
                  [13, 14]])
print(b)

print("--- dtypeを指定し、倍精度のTensorにする ---")
c = torch.tensor([[11, 12],
                  [13, 14]], dtype=torch.float64)
print(c)

print("--- 0から19までの数値で初期化 ---")
d = torch.arange(0, 20)
print(d)

print("--- すべての値が0の、3×4のTensor ---")
e = torch.zeros(3, 4)
print(e)

print("--- すべての値が乱数の、3×4のTensor ---")
f = torch.rand(3, 4)
print(f)

print("--- 形状はsizeメソッドで取得 ---")
print(f.size())

--- 2次元のリストから生成 ---
tensor([[11, 12],
        [13, 14]])
--- dtypeを指定し、倍精度のTensorにする ---
tensor([[11., 12.],
        [13., 14.]], dtype=torch.float64)
--- 0から19までの数値で初期化 ---
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
--- すべての値が0の、3×4のTensor ---
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
--- すべての値が乱数の、3×4のTensor ---
tensor([[0.4709, 0.5733, 0.2598, 0.1746],
        [0.9552, 0.1631, 0.2612, 0.3427],
        [0.5502, 0.6415, 0.5068, 0.7943]])
--- 形状はsizeメソッドで取得 ---
torch.Size([3, 4])


## TensorとNumPyの配列の相互変換
機械学習では、数値演算ライブラリNumPyの配列がよく使われます。  
以下は、TensorとNumPyの相互変換のコードです。  

In [4]:
print("--- Tensor → NumPy ---")
a = torch.tensor([[11, 12],
                  [13, 14]])
b = a.numpy()
print(b)

print("--- NumPy → Tensor ---")
c = torch.from_numpy(b)
print(c)

--- Tensor → NumPy ---
[[11 12]
 [13 14]]
--- NumPy → Tensor ---
tensor([[11, 12],
        [13, 14]])


## 範囲を指定してアクセス
Tensorの一部に、範囲を指定してアクセスすることができます。

In [10]:
a = torch.tensor([[11, 12, 13],
                  [14, 15, 16]])

print("--- 2つのインデックスを指定 ---")
print(a[1, 0])

print("--- 範囲を指定 ---")
print(a[0:2, :2])

print("--- 3より大きい要素のみを指定 ---")
print(a[a>13])

print("--- 要素の変更 ---")
a[0, 2] = 11
print(a)

print("--- ある次元の要素を一括変更 ---")
a[:, 1] = 22
print(a)

--- 2つのインデックスを指定 ---
tensor(14)
--- 範囲を指定 ---
tensor([[11, 12],
        [14, 15]])
--- 3より大きい要素のみを指定 ---
tensor([14, 15, 16])
--- 要素の変更 ---
tensor([[11, 12, 11],
        [14, 15, 16]])
--- ある次元の要素を一括変更 ---
tensor([[11, 22, 11],
        [14, 22, 16]])


## Tensorの演算
以下は、Tensor同士の演算の例です。

In [11]:
# ベクトル
a = torch.tensor([11, 12, 13]) 
b = torch.tensor([14, 15, 16])

# 行列
c = torch.tensor([[16, 15, 14],
                  [13, 12, 11]])

print("--- ベクトルとスカラーの演算 ---")
print(a + 3)

print("--- ベクトル同士の演算 ---")
print(a + b) 

print("--- 行列とスカラーの演算 ---")
print(c + 2)

print("--- 行列とベクトルの演算（ブロードキャスト） ---")
print(c + a)

print("--- 行列同士の演算 ---")
print(c + c)

--- ベクトルとスカラーの演算 ---
tensor([14, 15, 16])
--- ベクトル同士の演算 ---
tensor([25, 27, 29])
--- 行列とスカラーの演算 ---
tensor([[18, 17, 16],
        [15, 14, 13]])
--- 行列とベクトルの演算（ブロードキャスト） ---
tensor([[27, 27, 27],
        [24, 24, 24]])
--- 行列同士の演算 ---
tensor([[32, 30, 28],
        [26, 24, 22]])


ブロードキャストは、条件を満たしていれば形状が異なるTensor同士でも演算が可能になる機能です。

## Tensorの形状変換
`view()`を使えば、Tensorの形状を自由に変更することができます。

In [12]:
a = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11])  # 1次元のTensor
b = a.view(3, 4)  # (3, 4)の2次元のTensorに変換
print(b)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


引数のうち1つを-1にすれば、その次元の要素数は自動計算されます。  

In [13]:
c = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11])  # 1次元のTensor
d = c.view(3, -1)  # (3, 4)の2次元のTensorに変換
print(d)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


`view()`の引数を-1のみにすると、1次元に変換されます。  

In [19]:
e = torch.tensor([[[11, 12],
                   [13, 14]], 
                  [[15, 16],
                   [17, 18]]])  # 3次元のTensor
print(e)
f = e.view(-1)  # 1次元のTensorに変換
print(f)

print(e[1,0,0])

tensor([[[11, 12],
         [13, 14]],

        [[15, 16],
         [17, 18]]])
tensor([11, 12, 13, 14, 15, 16, 17, 18])
tensor(15)


## 統計値の計算
Tensorには、様々な統計値を計算する関数とメソッドが用意されています。  
Tensorから通常の値を取り出すためには、`item()`メソッドを使います。


In [23]:
a = torch.tensor([[11, 12, 13],
                  [14, 15, 16.]])

print("--- 平均値（関数） ---")
m = torch.mean(a)
print(m, type(m))
print(m.item())  # item()で値を取り出す

print("--- 平均値（メソッド） ---")
m = a.mean()
print(m.item())

print("--- 列ごとの平均値 ---")
print(a.mean(0))

print("--- 合計値 ---")
print(torch.sum(a).item())

print("--- 最大値 ---")
print(torch.max(a).item())

print("--- 最小値 ---")
print(torch.min(a).item())

--- 平均値（関数） ---
tensor(13.5000) <class 'torch.Tensor'>
13.5
--- 平均値（メソッド） ---
13.5
--- 列ごとの平均値 ---
tensor([12.5000, 13.5000, 14.5000])
--- 合計値 ---
81.0
--- 最大値 ---
16.0
--- 最小値 ---
11.0


今回扱ったTensorの機能はごく一部です。  
詳しくは、以下の公式ドキュメントを参考にしてください。  
https://pytorch.org/docs/stable/tensors.html