<a href="https://colab.research.google.com/github/yukinaga/image_classification/blob/main/section_1/02_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 演習
Tensor同士の演算を練習しましょう。  

## Tensor同士の演算
以下のコードにおけるTensor、`a`と`b`の間で演算を行い、結果を表示しましょう。  
`a`は2次元のTensorで`b`は1次元のTensorなので、ブロードキャストが必要です。  

In [10]:
import torch

a = torch.tensor([[11, 12, 13],
                  [14, 15, 16]])
b = torch.tensor([1, 2, 3]) 

print("--- 和 ---")
print(a + b)


print("--- 差 ---")
print(a - b)

print("--- 積 ---")
print(a * b)


print("--- 商（小数） ---")
print(a / b)

print("--- 商（整数） ---")
print(a // b)


print("--- 余り ---")
print(a % b)


--- 和 ---
tensor([[12, 14, 16],
        [15, 17, 19]])
--- 差 ---
tensor([[10, 10, 10],
        [13, 13, 13]])
--- 積 ---
tensor([[11, 24, 39],
        [14, 30, 48]])
--- 商（小数） ---
tensor([[11.0000,  6.0000,  4.3333],
        [14.0000,  7.5000,  5.3333]])
--- 商（整数） ---
tensor([[11,  6,  4],
        [14,  7,  5]])
--- 余り ---
tensor([[0, 0, 1],
        [0, 1, 1]])


### 〇解答例
以下は解答例です。

In [ ]:
import torch

a = torch.tensor([[11, 12, 13],
                  [14, 15, 16]])
b = torch.tensor([1, 2, 3]) 

print("--- 和 ---")
print(a + b)

print("--- 差 ---")
print(a - b)

print("--- 積 ---")
print(a * b)

print("--- 商（小数） ---")
print(a / b)

print("--- 商（整数） ---")
print(a // b)

print("--- 余り ---")
print(a % b)